language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=latest PACKAGE=mirage-seal
    UPDATE_GCC_BINUTILS=1
    POST_INSTALL_HOOK="./test.sh"
